### ISSUE TITLE
IllegalArgumentException at org.jpmml.tensorflow.EstimatorFactory.newEstimator

### ISSUE THREAD

**Issue by calebstrait** [jpmml/jpmml-tensorflow#14]
Dear Villu,
With-
protobuf 3.7.1
tensorflow 1.13.1
openjdk 1.8.0_212
I'm doing
`$ java -jar target/converter-executable-1.0-SNAPSHOT.jar --tf-savedmodel-input 1554735764/ --pmml-output estimator.pmml`
to the following error:
```
Apr 09, 2019 1:39:36 PM org.jpmml.tensorflow.Main run
INFO: Parsing SavedModel..
2019-04-09 13:39:38.108054: I tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: /home/cstrait_gcp2/1554735764
2019-04-09 13:39:38.144966: I tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { serve }
2019-04-09 13:39:38.150964: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-04-09 13:39:38.221977: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2019-04-09 13:39:38.222114: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x7ff2d4d0c8b0 executing computations on platform Host. Devices:
2019-04-09 13:39:38.222125: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-04-09 13:39:38.243759: I tensorflow/cc/saved_model/loader.cc:182] Restoring SavedModel bundle.
2019-04-09 13:39:38.431421: I tensorflow/cc/saved_model/loader.cc:132] Running initialization op on SavedModel bundle.
2019-04-09 13:39:38.463896: I tensorflow/cc/saved_model/loader.cc:285] SavedModel load for tags { serve }; Status: success. Took 355847 microseconds.
Apr 09, 2019 1:39:38 PM org.jpmml.tensorflow.Main run
INFO: Parsed SavedModel in 1622 ms.
Apr 09, 2019 1:39:39 PM org.jpmml.tensorflow.Main run
INFO: Converting..
Apr 09, 2019 1:39:39 PM org.jpmml.tensorflow.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException
        at org.jpmml.tensorflow.EstimatorFactory.newEstimator(EstimatorFactory.java:58)
        at org.jpmml.tensorflow.Main.run(Main.java:117)
        at org.jpmml.tensorflow.Main.main(Main.java:90)

Exception in thread "main" java.lang.IllegalArgumentException
        at org.jpmml.tensorflow.EstimatorFactory.newEstimator(EstimatorFactory.java:58)
        at org.jpmml.tensorflow.Main.run(Main.java:117)
        at org.jpmml.tensorflow.Main.main(Main.java:90)
```
I'd truly appreciate any assistance in you can offer in debugging this, which I suspect is a versions-related issue.
Regards,
Caleb

**Comment by vruusmann** [comment]
> tensorflow 1.13.1

This project was last updated for TensorFlow 1.3.0 (ten major releases back).

Predictive Model Markup Language (PMML) is addressing the structured data science domain, and is not particularly compatible/relevant for  unstructured data. Didn't know it at the time when the JPMML-TensorFlow project was started.

Time to mark this project as "Archived".
