### ISSUE TITLE
SEVERE: Failed to convert (IllegalArgumentException)

### ISSUE THREAD

**Issue by chloejia** [jpmml/jpmml-tensorflow#4]
Hi @vruusmann,

I wish to convert my `contrib.learn.DNNClassifier` estimator to PMML, but came across:
```
SEVERE: Failed to convert
java.lang.IllegalArgumentException
	at org.jpmml.tensorflow.DNNEstimator.encodeNeuralNetwork(DNNEstimator.java:77)
	at org.jpmml.tensorflow.DNNClassifier.encodeModel(DNNClassifier.java:50)
	at org.jpmml.tensorflow.DNNClassifier.encodeModel(DNNClassifier.java:40)
	at org.jpmml.tensorflow.Estimator.encodePMML(Estimator.java:43)
	at org.jpmml.tensorflow.Main.run(Main.java:120)
	at org.jpmml.tensorflow.Main.main(Main.java:90)

Exception in thread "main" java.lang.IllegalArgumentException
	at org.jpmml.tensorflow.DNNEstimator.encodeNeuralNetwork(DNNEstimator.java:77)
	at org.jpmml.tensorflow.DNNClassifier.encodeModel(DNNClassifier.java:50)
	at org.jpmml.tensorflow.DNNClassifier.encodeModel(DNNClassifier.java:40)
	at org.jpmml.tensorflow.Estimator.encodePMML(Estimator.java:43)
	at org.jpmml.tensorflow.Main.run(Main.java:120)
	at org.jpmml.tensorflow.Main.main(Main.java:90)
```

I was trying to look into this, and the println of [`NodeDef concat`](https://github.com/jpmml/jpmml-tensorflow/blob/master/src/main/java/org/jpmml/tensorflow/DNNEstimator.java#L73) looks like:
```
name: "dnn/input_from_feature_columns/input_from_feature_columns/concat"
op: "Identity"
input: "ParseExample/ParseExample"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "_output_shapes"
  value {
    list {
      shape {
        dim {
          size: -1
        }
        dim {
          size: 119
        }
      }
    }
  }
```
seems like a structure conflict?  And I was using TF v1.5.

@vruusmann Is this normal behavior? Or any clue how I can fix this? 

Thanks very much for sharing us this tool !!! 👍 💯

**Comment by vruusmann** [comment]
> java.lang.IllegalArgumentException
>   at org.jpmml.tensorflow.DNNEstimator.encodeNeuralNetwork(DNNEstimator.java:77)

Have you updated to the latest JPMML-TensorFlow version?

The line 77 of `DNNEstimator.java` currently reads:
```Java
List<Feature> features = new ArrayList<>();
```

I don't see how that can throw an IllegalArgumentException.

**Comment by chloejia** [comment]
> The line 77 of DNNEstimator.java currently reads:

sorry, coz I added some lines w/ `System.out.println`
