### ISSUE TITLE
tensorflow convert the pmml exception

### ISSUE THREAD

**Issue by lijunyong** [jpmml/jpmml-tensorflow#8]
```
root@main:/opt# java -jar converter-executable-1.0-SNAPSHOT.jar --tf-savedmodel-input model/ --pmml-output estimator.pmml
Mar 12, 2018 9:35:02 AM org.jpmml.tensorflow.Main run
INFO: Parsing SavedModel..
2018-03-12 09:35:02.866322: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-03-12 09:35:02.866705: I tensorflow/cc/saved_model/loader.cc:289] SavedModel load for tags { serve }; Status: fail. Took 24 microseconds.
Mar 12, 2018 9:35:02 AM org.jpmml.tensorflow.Main run
SEVERE: Failed to parse SavedModel
org.tensorflow.TensorFlowException: SavedModel not found in export directory: /opt/model
	at org.tensorflow.SavedModelBundle.load(Native Method)
	at org.tensorflow.SavedModelBundle.load(SavedModelBundle.java:39)
	at org.jpmml.tensorflow.Main.run(Main.java:100)
	at org.jpmml.tensorflow.Main.main(Main.java:90)

Exception in thread "main" org.tensorflow.TensorFlowException: SavedModel not found in export directory: /opt/model
	at org.tensorflow.SavedModelBundle.load(Native Method)
	at org.tensorflow.SavedModelBundle.load(SavedModelBundle.java:39)
	at org.jpmml.tensorflow.Main.run(Main.java:100)
	at org.jpmml.tensorflow.Main.main(Main.java:90)
```

my os system is ubuntu 16.04
```
root@main:/opt/model# pwd
/opt/model
root@main:/opt/model# ls
checkpoint                             mnist_model-26001.data-00000-of-00001  mnist_model-27001.index                mnist_model-28001.meta
mnist_model-25001.data-00000-of-00001  mnist_model-26001.index                mnist_model-27001.meta                 mnist_model-29001.data-00000-of-00001
mnist_model-25001.index                mnist_model-26001.meta                 mnist_model-28001.data-00000-of-00001  mnist_model-29001.index
mnist_model-25001.meta                 mnist_model-27001.data-00000-of-00001  mnist_model-28001.index                mnist_model-29001.meta
root@main:/opt/model# 

```

**Comment by vruusmann** [comment]
Like the exception message suggests, your `/opt/model` directory does not seem to contain a TensorFlow model in "SavedModel" data format.

Sure, it contains a bunch of files, but they are not "SavedModel" files. For example, there is no `saved_model.pbtxt` file.

**Comment by lijunyong** [comment]
@vruusmann thanks a lot，I cpoy the 'src/test/resources/savedmodel/DNNRegressionAuto/saved_model.pbtxt' to '/opt/model', the I get execption:
```
root@main:/opt# java -jar converter-executable-1.0-SNAPSHOT.jar --tf-savedmodel-input /opt/model/ --pmml-output ai-cloud.pmml
Mar 14, 2018 2:24:41 PM org.jpmml.tensorflow.Main run
INFO: Parsing SavedModel..
2018-03-14 14:24:41.402997: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-03-14 14:24:41.403272: I tensorflow/cc/saved_model/loader.cc:240] Loading SavedModel with tags: { serve }; from: /opt/model
2018-03-14 14:24:41.433724: I tensorflow/cc/saved_model/loader.cc:159] Restoring SavedModel bundle.
2018-03-14 14:24:41.433807: I tensorflow/cc/saved_model/loader.cc:169] The specified SavedModel has no variables; no checkpoints were restored.
2018-03-14 14:24:41.433838: I tensorflow/cc/saved_model/loader.cc:194] Running LegacyInitOp on SavedModel bundle.
2018-03-14 14:24:41.443690: I tensorflow/cc/saved_model/loader.cc:289] SavedModel load for tags { serve }; Status: success. Took 40300 microseconds.
Mar 14, 2018 2:24:41 PM org.jpmml.tensorflow.Main run
INFO: Parsed SavedModel in 433 ms.
Mar 14, 2018 2:24:41 PM org.jpmml.tensorflow.Main run
INFO: Converting..
Mar 14, 2018 2:24:41 PM org.jpmml.tensorflow.Main run
SEVERE: Failed to convert
java.lang.IllegalStateException: Attempting to use uninitialized value dnn/hiddenlayer_0/weights/part_0
	 [[Node: _retval_dnn/hiddenlayer_0/weights/part_0_0_0 = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](dnn/hiddenlayer_0/weights/part_0)]]
	at org.tensorflow.Session.run(Native Method)
	at org.tensorflow.Session.access$100(Session.java:48)
	at org.tensorflow.Session$Runner.runHelper(Session.java:298)
	at org.tensorflow.Session$Runner.run(Session.java:248)
	at org.jpmml.tensorflow.SavedModel.run(SavedModel.java:136)
	at org.jpmml.tensorflow.DNNEstimator.encodeNeuralNetwork(DNNEstimator.java:149)
	at org.jpmml.tensorflow.DNNRegressor.encodeModel(DNNRegressor.java:46)
	at org.jpmml.tensorflow.DNNRegressor.encodeModel(DNNRegressor.java:36)
	at org.jpmml.tensorflow.Estimator.encodePMML(Estimator.java:43)
	at org.jpmml.tensorflow.Main.run(Main.java:120)
	at org.jpmml.tensorflow.Main.main(Main.java:90)

Exception in thread "main" java.lang.IllegalStateException: Attempting to use uninitialized value dnn/hiddenlayer_0/weights/part_0
	 [[Node: _retval_dnn/hiddenlayer_0/weights/part_0_0_0 = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](dnn/hiddenlayer_0/weights/part_0)]]
	at org.tensorflow.Session.run(Native Method)
	at org.tensorflow.Session.access$100(Session.java:48)
	at org.tensorflow.Session$Runner.runHelper(Session.java:298)
	at org.tensorflow.Session$Runner.run(Session.java:248)
	at org.jpmml.tensorflow.SavedModel.run(SavedModel.java:136)
	at org.jpmml.tensorflow.DNNEstimator.encodeNeuralNetwork(DNNEstimator.java:149)
	at org.jpmml.tensorflow.DNNRegressor.encodeModel(DNNRegressor.java:46)
	at org.jpmml.tensorflow.DNNRegressor.encodeModel(DNNRegressor.java:36)
	at org.jpmml.tensorflow.Estimator.encodePMML(Estimator.java:43)
	at org.jpmml.tensorflow.Main.run(Main.java:120)
	at org.jpmml.tensorflow.Main.main(Main.java:90)
root@main:/opt# 

```

**Comment by vruusmann** [comment]
You cannot copy my `saved_model.pbtxt` into your directory to make it a "SavedModel" directory - they represent different computation problems.

You must order TensorFlow to generate a proper "SavedModel" directory. At the moment it seems to contain a lot of intermediate step files (eg. `checkpoint` file), which shows that it's not a final state.

**Comment by lijunyong** [comment]
@vruusmann Thank you very much, you are so nice
